### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by AltNico** [hw-manager/android#4]
*Like Devin said: "I think that instead of a Button Bar, use a Floating Action Button."*
*Here is the commit for the floating action button in Flym (Feed Reader):*
*https://github.com/FredJul/Flym/commit/569ab615109de4ce76c7faad50eb92118c0b19ce*

Originally [here](https://github.com/AltNico/ha-manager/issues/27).

**Comment by Arya766** [comment]
As a start, it would be very nice if it had dark/light themes.

**Comment by easyaspi314** [comment]
It currently uses the Theme.Material.Light.DarkActionBar theme. So what I was saying was a color scheme, like what the Play Store does when you switch sections, the app changes colors.

**Comment by Arya766** [comment]
@easyaspi314 since it's not a cli app, it has to have a gui. That's not what I meant. Now it only has one theme; the light one. I meant users have a choice between dark and light themes, like Wikipedia app if you've seen. It is easy to do, yet has a good impact on users as battery usage is always a challenge, and screen drains most of it.

**Comment by easyaspi314** [comment]
I suppose. I am good at theme switching (see easyaspi314/Notepad where I literally have all sorts of themes to switch between. I can take this on.

**Comment by Arya766** [comment]
@easyaspi314 great!

**Comment by easyaspi314** [comment]
@Arya766 Thanks!

**Comment by Arya766** [comment]
@easyaspi314 thank you actually! You did the code.

**Comment by AltNico** [comment]
I think, we can close this, as devices on Android 5+ has the Material theme and all others has their supposed theme too.
