### ISSUE TITLE
Select file to import

### ISSUE THREAD

**Issue by AltNico** [hw-manager/android#9]
Current workflow:
Menu -> Import Homework => Homework imported

Suggested workflow:
Menu -> Import Homework -> Select file to import => Selected homework imported

**Comment by easyaspi314** [comment]
Check out my pull request.

**Comment by Arya766** [comment]
If you're going to add "import" option, you'll have to have added "export". How can you import somwthing you haven't exported previously?

**Comment by AltNico** [comment]
@Arya766 HW-Manager already has an export option in the preferences.

**Comment by Arya766** [comment]
I know it has; if you're talking about that option, it has import too. If it is about importing one single/ selected homework(s) as a file, it needs export too.

**Comment by AltNico** [comment]
@Arya766 No, I mean importing the whole database, not just one homework.

**Comment by Arya766** [comment]
Well it's already there. You have both export and import. The only thing you can add, imo, is to have a default address, and an option to select it. (For both import and export)

**Comment by easyaspi314** [comment]
Let me explain what my current method does:
1. Export now has the filename Homework-2015-01-24-10:28.db (not locally formatted because it is easier for the filesystem to sort). We still need to change the string. We could have an EditText that sets its text to that format, but allows it to be saved as a different name.

2. Import shows a dialog that shows the files in /sdcard/HW-Manager (or whatever the app’s default backup path is) and you click an item and it imports that backup. It also trims the file extension, using a snippet of code from Apache Commons IO library. 

I would like to force only files ending with .db to show (more FilenameUtils stuff). For now, this is the way it shows up:
/sdcard/HW-Manager directory example:
Homework-2015-01-24-10:28.db
Homework.db
Preferences.xml

The way it shows up:
___________________________
|  Import					      |
———————————————|
|  Homework-2015-01-24-10:28    |
|  Homework   				      |
|  Preferences 				      |
———————————————|
|           	   Cancel			      |
———————————————|

**Comment by easyaspi314** [comment]
And I fixed it in my latest commit.

And this.
![device-2015-01-24-191403](https://cloud.githubusercontent.com/assets/6258309/5891629/a99e5eba-a46e-11e4-9e54-d83f3a1d989f.png)

**Comment by AltNico** [comment]
Fixed with 6bec218b7fb494c15391ddebaafa27f0348f83cc
